# Generated by Django 2.0.2 on 2018-02-19 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symbol', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=500)),
                ('MarketCap', models.FloatField()),
                ('Sector', models.CharField(max_length=500)),
                ('Industry', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ['Symbol'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('marketsym', models.CharField(max_length=20)),
                ('openp', models.FloatField()),
                ('closep', models.FloatField()),
                ('low', models.FloatField()),
                ('high', models.FloatField()),
                ('volume', models.FloatField()),
                ('symbol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='csv2db.company')),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
    ]
